CREATE TABLE `project_actions_v3` (
	`id` int AUTO_INCREMENT NOT NULL,
	`client_id` int NOT NULL,
	`project_id` int NOT NULL,
	`requirement_code` varchar(32) NOT NULL,
	`risk_code` varchar(32) NOT NULL,
	`domain` varchar(100) NOT NULL,
	`gap_type` enum('normativo','processo','sistema','cadastro','contrato','financeiro','acessorio') NOT NULL,
	`action_code` varchar(32) NOT NULL,
	`action_name` varchar(255) NOT NULL,
	`action_desc` text NOT NULL,
	`action_type` enum('configuracao_erp','ajuste_cadastro','revisao_contrato','parametrizacao_fiscal','obrigacao_acessoria','documentacao','treinamento','integracao','governanca','conciliacao') NOT NULL,
	`action_priority` enum('imediata','curto_prazo','medio_prazo','planejamento') NOT NULL,
	`estimated_days` int NOT NULL,
	`due_date` timestamp,
	`owner_suggestion` varchar(255) NOT NULL,
	`status` enum('nao_iniciado','em_andamento','em_revisao','concluido','cancelado') NOT NULL DEFAULT 'nao_iniciado',
	`progress_percent` int NOT NULL DEFAULT 0,
	`completed_at` timestamp,
	`analysis_version` int NOT NULL DEFAULT 1,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `project_actions_v3_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `project_assessments_v3` (
	`id` int AUTO_INCREMENT NOT NULL,
	`client_id` int NOT NULL,
	`project_id` int NOT NULL,
	`requirement_code` varchar(32) NOT NULL,
	`criteria_coverage` decimal(5,2) NOT NULL,
	`evidence_coverage` decimal(5,2) NOT NULL,
	`operational_readiness` decimal(5,2) NOT NULL,
	`ai_score` decimal(5,2),
	`notes` text,
	`analysis_version` int NOT NULL DEFAULT 1,
	`answered_by_id` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `project_assessments_v3_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `project_gaps_v3` (
	`id` int AUTO_INCREMENT NOT NULL,
	`client_id` int NOT NULL,
	`project_id` int NOT NULL,
	`requirement_code` varchar(32) NOT NULL,
	`requirement_name` varchar(255) NOT NULL,
	`domain` varchar(100) NOT NULL,
	`gap_level` enum('estrategico','tatico','operacional','tecnico') NOT NULL,
	`gap_type` enum('normativo','processo','sistema','cadastro','contrato','financeiro','acessorio') NOT NULL,
	`compliance_status` enum('atendido','parcialmente_atendido','nao_atendido','nao_aplicavel') NOT NULL,
	`criticality` enum('baixa','media','alta','critica') NOT NULL,
	`evidence_status` enum('completa','parcial','ausente') NOT NULL,
	`operational_dependency` enum('alta','media','baixa') NOT NULL,
	`score` decimal(5,2) NOT NULL,
	`risk_level` enum('baixo','medio','alto','critico') NOT NULL,
	`priority_score` decimal(5,2) NOT NULL,
	`critical_evidence_flag` boolean NOT NULL DEFAULT false,
	`action_priority` enum('imediata','curto_prazo','medio_prazo','planejamento') NOT NULL,
	`estimated_days` int NOT NULL,
	`gap_description` text NOT NULL,
	`deterministic_reason` text NOT NULL,
	`ai_reason` text,
	`unmet_criteria` text NOT NULL,
	`recommended_actions` text NOT NULL,
	`analysis_version` int NOT NULL DEFAULT 1,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `project_gaps_v3_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `project_risks_v3` (
	`id` int AUTO_INCREMENT NOT NULL,
	`client_id` int NOT NULL,
	`project_id` int NOT NULL,
	`risk_code` varchar(32) NOT NULL,
	`requirement_code` varchar(32) NOT NULL,
	`requirement_name` varchar(255) NOT NULL,
	`domain` varchar(100) NOT NULL,
	`gap_type` enum('normativo','processo','sistema','cadastro','contrato','financeiro','acessorio') NOT NULL,
	`probability` int NOT NULL,
	`impact` int NOT NULL,
	`risk_score` int NOT NULL,
	`risk_score_normalized` int NOT NULL,
	`risk_level` enum('baixo','medio','alto','critico') NOT NULL,
	`risk_dimension` enum('regulatorio','operacional','financeiro','reputacional') NOT NULL,
	`financial_impact_percent` decimal(5,4) NOT NULL,
	`financial_impact_description` text NOT NULL,
	`mitigation_strategy` text NOT NULL,
	`analysis_version` int NOT NULL DEFAULT 1,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `project_risks_v3_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `project_scores_v3` (
	`id` int AUTO_INCREMENT NOT NULL,
	`client_id` int NOT NULL,
	`project_id` int NOT NULL,
	`requirement_code` varchar(32) NOT NULL,
	`criteria_coverage` decimal(5,2) NOT NULL,
	`evidence_coverage` decimal(5,2) NOT NULL,
	`operational_readiness` decimal(5,2) NOT NULL,
	`base_score` decimal(5,2) NOT NULL,
	`weighted_score` decimal(5,2) NOT NULL,
	`ai_score` decimal(5,2),
	`final_score` decimal(5,2) NOT NULL,
	`compliance_status` enum('atendido','parcialmente_atendido','nao_atendido','nao_aplicavel') NOT NULL,
	`risk_level` enum('baixo','medio','alto','critico') NOT NULL,
	`effective_criticality` enum('baixa','media','alta','critica') NOT NULL,
	`critical_evidence_flag` boolean NOT NULL DEFAULT false,
	`gap_type` enum('normativo','processo','sistema','cadastro','contrato','financeiro','acessorio') NOT NULL,
	`analysis_version` int NOT NULL DEFAULT 1,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `project_scores_v3_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `project_snapshots_v3` (
	`id` int AUTO_INCREMENT NOT NULL,
	`client_id` int NOT NULL,
	`project_id` int NOT NULL,
	`analysis_version` int NOT NULL,
	`confidence_score_global` decimal(5,2) NOT NULL,
	`confidence_breakdown` text NOT NULL,
	`radar_json` text NOT NULL,
	`risk_summary_json` text NOT NULL,
	`action_summary_json` text NOT NULL,
	`task_summary_json` text NOT NULL,
	`overall_score` decimal(5,2) NOT NULL,
	`total_requirements` int NOT NULL,
	`total_gaps` int NOT NULL,
	`critical_gaps` int NOT NULL,
	`total_risks` int NOT NULL,
	`critical_risks` int NOT NULL,
	`total_actions` int NOT NULL,
	`immediate_actions` int NOT NULL,
	`executive_summary_json` text,
	`generated_by` enum('deterministic','ai') NOT NULL DEFAULT 'deterministic',
	`valid_until` timestamp,
	`is_stale` boolean NOT NULL DEFAULT false,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `project_snapshots_v3_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `project_tasks_v3` (
	`id` int AUTO_INCREMENT NOT NULL,
	`client_id` int NOT NULL,
	`project_id` int NOT NULL,
	`action_code` varchar(32) NOT NULL,
	`requirement_code` varchar(32) NOT NULL,
	`task_code` varchar(32) NOT NULL,
	`task_name` varchar(255) NOT NULL,
	`task_desc` text NOT NULL,
	`task_type` enum('analise','documentacao','configuracao','treinamento','validacao','aprovacao','comunicacao','integracao','teste','go_live') NOT NULL,
	`owner_type` varchar(100) NOT NULL,
	`estimated_days` int NOT NULL,
	`execution_order` int NOT NULL,
	`depends_on` text NOT NULL,
	`status` enum('nao_iniciado','em_andamento','em_revisao','concluido','bloqueado') NOT NULL DEFAULT 'nao_iniciado',
	`progress_percent` int NOT NULL DEFAULT 0,
	`completion_criteria` text NOT NULL,
	`completed_at` timestamp,
	`analysis_version` int NOT NULL DEFAULT 1,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `project_tasks_v3_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `regulatory_requirements_v3` (
	`id` int AUTO_INCREMENT NOT NULL,
	`code` varchar(32) NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text NOT NULL,
	`domain` varchar(100) NOT NULL,
	`assessment_order` int NOT NULL,
	`base_criticality` enum('baixa','media','alta','critica') NOT NULL,
	`default_gap_type` enum('normativo','processo','sistema','cadastro','contrato','financeiro','acessorio') NOT NULL,
	`gap_level` enum('estrategico','tatico','operacional','tecnico') NOT NULL,
	`evaluation_criteria` text NOT NULL,
	`evidence_required` text NOT NULL,
	`tags` text,
	`legal_reference` varchar(255),
	`legal_article` varchar(100),
	`active` boolean NOT NULL DEFAULT true,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `regulatory_requirements_v3_id` PRIMARY KEY(`id`),
	CONSTRAINT `regulatory_requirements_v3_code_unique` UNIQUE(`code`)
);
